<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.RazorPages" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\01_ShoppingSiteQuery\01_ShoppingSiteQuery.csproj" />
    <ProjectReference Include="..\ShoppingSiteManagement.Infrastructure.Config\ShoppingSiteManagement.Infrastructure.Config.csproj" />
    <ProjectReference Include="..\ShoppingSiteManagement.Infrastructure.EFCore\ShoppingSiteManagement.Infrastructure.EFCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Theme\assets\images\menu-main\card\" />
  </ItemGroup>

</Project>
